name: Code coverage report
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - rel-v*
env:
  CARGO_TERM_COLOR: always
  CI: true
permissions:
  contents: read

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup for testing
        run: |
          mkdir grcov
          curl -sL https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | (cd grcov ; tar jxf -)
          rustup toolchain add stable --component llvm-tools-preview
          rustup override set stable

      - name: Test
        env:
          CI: true
          RUSTFLAGS: -Cinstrument-coverage
          LLVM_PROFILE_FILE: dragonfly-%p-%m.profraw
          RUST_LOG: debug
        run: |
          cargo build
          cargo test

      - name: Generate coverage
        run: |
          grcov/grcov $(find . -name "dragonfly-*.profraw" -print) \
            --branch \
            --ignore-not-existing \
            --binary-path ./target/debug/ \
            -s src \
            -t lcov \
            --ignore "/*" \
            --excl-line '^\s*\.await\??;?$' --excl-br-line '^\s*\.await\??;?$' \
            -o lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: ./lcov.info
